[package]
name = "ailloli_ui_fs_local"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Local filesystem provider and native watcher for Ailloli UI"
documentation = "https://ailloliai.github.io/ailloli_ui/ailloli_ui_fs_local/"
keywords = ["filesystem", "local", "watcher", "provider", "rust"]
categories = ["filesystem"]
publish.workspace = true

[dependencies]
ailloli_ui_fs = { path = "../ailloli_ui_fs" }
notify = { workspace = true }
