[package]
name = "ailloli_ui_runtime"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
devtools = []

[dependencies]
ailloli_ui_core = { path = "../ailloli_ui_core" }
ailloli_ui_text = { path = "../ailloli_ui_text" }
thiserror.workspace = true
url.workspace = true
