[package]
name = "ailloli_ui_text"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Text shaping, layout, wrapping, and editable buffers for Ailloli UI"
documentation = "https://ailloliai.github.io/ailloli_ui/ailloli_ui_text/"
keywords = ["text", "layout", "fonts", "shaping", "editor"]
categories = ["text-processing"]
readme = "README.md"
publish.workspace = true

[dependencies]
ailloli_ui_core.workspace = true
fontdue.workspace = true
parley.workspace = true
fontique.workspace = true
lru.workspace = true
ropey.workspace = true
unicode-segmentation.workspace = true
