//! Neutral frame outputs and per-frame diagnostic counters.

use crate::layout::EditorTextRun;
use crate::{EditorPaintItem, EditorViewport};
use ailloli_ui_core::Size;

/// Per-frame performance counters measured by the editor engine.
///
/// Times are integer microseconds and may be zero below clock resolution.
/// Counts are per frame; `used_fast_path` reports the large-document path.
///
/// # Examples
///
/// ```
/// use ailloli_ui_editor::EditorFrameDebugMetrics;
/// let name = std::any::type_name::<EditorFrameDebugMetrics>();
/// assert!(name.ends_with("EditorFrameDebugMetrics"));
/// ```
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct EditorFrameDebugMetrics {
    /// Monotonically wrapping engine frame ID.
    pub frame_id: u64,
    /// Visible paragraph layout time in microseconds.
    pub visible_layout_us: u64,
    /// Paragraph layouts reused from cache.
    pub paragraph_cache_hits: usize,
    /// Paragraph layouts newly prepared.
    pub paragraph_cache_misses: usize,
    /// Syntax refresh time in microseconds.
    pub syntax_parse_us: u64,
    /// Symbol indexing time in microseconds.
    pub symbol_index_us: u64,
    /// Number of neutral paint items emitted.
    pub paint_item_count: usize,
    /// Glyph uploads attributed by the adapter; zero in engine-only frames.
    pub glyph_upload_count: usize,
    /// Whether large-document fast-path thresholds selected reduced work.
    pub used_fast_path: bool,
}

/// Complete editor frame generated by the engine for one viewport.
///
/// # Examples
///
/// ```
/// use ailloli_ui_editor::EditorFrame;
/// fn inspect(frame: &EditorFrame) {
///     assert_eq!(frame.debug_metrics.paint_item_count, frame.paint_items.len());
/// }
/// ```
#[derive(Debug, Clone)]
pub struct EditorFrame {
    /// Resolved widget/content/text/gutter geometry.
    pub viewport: EditorViewport,
    /// Full logical-pixel content size before viewport clipping.
    pub content_size: Size,
    /// Visible shaped paragraph runs.
    pub runs: Vec<EditorTextRun>,
    /// Adapter-neutral ordered paint commands.
    pub paint_items: Vec<EditorPaintItem>,
    /// Source paragraph indices represented in `runs`.
    pub painted_paragraphs: Vec<usize>,
    /// Work and timing counters for this frame.
    pub debug_metrics: EditorFrameDebugMetrics,
}
