use crate::layout::EditorTextRun;
use crate::{EditorPaintItem, EditorViewport};
use ailloli_ui_core::Size;

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct EditorFrameDebugMetrics {
    pub frame_id: u64,
    pub visible_layout_us: u64,
    pub paragraph_cache_hits: usize,
    pub paragraph_cache_misses: usize,
    pub syntax_parse_us: u64,
    pub symbol_index_us: u64,
    pub paint_item_count: usize,
    pub glyph_upload_count: usize,
    pub used_fast_path: bool,
}

/// Complete editor frame generated by the engine for one viewport.
#[derive(Debug, Clone)]
pub struct EditorFrame {
    pub viewport: EditorViewport,
    pub content_size: Size,
    pub runs: Vec<EditorTextRun>,
    pub paint_items: Vec<EditorPaintItem>,
    pub painted_paragraphs: Vec<usize>,
    pub debug_metrics: EditorFrameDebugMetrics,
}
