[package]
name = "ailloli_ui"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = ["winit"]
winit = ["dep:ailloli_ui_winit", "dep:ailloli_ui_render_wgpu"]
native-overlay = ["winit", "ailloli_ui_winit/native-overlay"]
tree-sitter = ["ailloli_ui_widgets/tree-sitter"]
files = ["ailloli_ui_widgets/files"]
files-local = ["files", "ailloli_ui_widgets/files-local"]
terminal-pty = ["dep:ailloli_ui_terminal_pty"]
terminal-pty-portable = ["terminal-pty", "ailloli_ui_terminal_pty/portable"]
devtools = [
    "dep:ailloli_ui_devtools_core",
    "dep:ailloli_ui_devtools_ui",
    "ailloli_ui_runtime/devtools",
    "ailloli_ui_winit?/devtools",
]
devtools-terminal = [
    "devtools",
    "ailloli_ui_devtools_core/terminal",
    "ailloli_ui_devtools_ui/terminal",
]

[dependencies]
ailloli_ui_app_storage = { path = "../ailloli_ui_app_storage" }
ailloli_ui_core = { path = "../ailloli_ui_core" }
ailloli_ui_fs = { path = "../ailloli_ui_fs" }
ailloli_ui_runtime = { path = "../ailloli_ui_runtime" }
ailloli_ui_terminal_core = { path = "../ailloli_ui_terminal_core" }
ailloli_ui_terminal_pty = { path = "../ailloli_ui_terminal_pty", optional = true }
ailloli_ui_text = { path = "../ailloli_ui_text" }
ailloli_ui_widgets = { path = "../ailloli_ui_widgets" }
ailloli_ui_icon = { path = "../ailloli_ui_icon" }
ailloli_ui_devtools_core = { path = "../ailloli_ui_devtools_core", optional = true }
ailloli_ui_devtools_ui = { path = "../ailloli_ui_devtools_ui", optional = true }
ailloli_ui_winit = { path = "../ailloli_ui_winit", optional = true }
ailloli_ui_render_wgpu = { path = "../ailloli_ui_render_wgpu", optional = true }
serde_json.workspace = true
