[package]
name = "ailloli_ui_terminal_pty"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
portable = ["dep:portable-pty"]

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
portable-pty = { workspace = true, optional = true }
